import AppLayout from '@/layouts/app-layout'
import { BreadcrumbItem } from '@/types'
import { Head } from '@inertiajs/react'
import StoreCategoryForm from './components/store-category-form'
import { StoreCategory } from '@/types/dashboard'

// Routes will be auto-generated by wayfinder
const storeCategoryRoutes = {
    index: { url: () => '/admin/store-categories' },
    create: { url: () => '/admin/store-categories/create' },
}

const breadcrumbs: BreadcrumbItem[] = [
    {
        title: 'Store Categories',
        href: storeCategoryRoutes.index.url(),
    },
    {
        title: 'Create Store Category',
        href: storeCategoryRoutes.create.url(),
    },
]

const StoreCategoriesCreate = ({ category }: { category: StoreCategory }) => {
    return (
        <AppLayout breadcrumbs={breadcrumbs} >
            <Head title="Create Store Category" />
            <div className="flex h-full flex-1 flex-col gap-4 overflow-x-auto rounded-xl p-4">
                <StoreCategoryForm category={category} type="create" />
            </div>
        </AppLayout >
    )
}

export default StoreCategoriesCreate

