import AppLayout from '@/layouts/app-layout'
import { BreadcrumbItem } from '@/types'
import { StoreCategory } from '@/types/dashboard'
import { Head } from '@inertiajs/react'
import StoreCategoryForm from './components/store-category-form'

// Routes will be auto-generated by wayfinder
const storeCategoryRoutes = {
    index: { url: () => '/admin/store-categories' },
    edit: { url: (args: { 'store-category': string | number }) => `/admin/store-categories/${args['store-category']}/edit` },
}

const StoreCategoriesEdit = ({ category }: { category: StoreCategory }) => {
    const breadcrumbs: BreadcrumbItem[] = [
        {
            title: 'Store Categories',
            href: storeCategoryRoutes.index.url(),
        },
        {
            title: 'Edit Store Category',
            href: storeCategoryRoutes.edit.url({ 'store-category': category.id }),
        },
    ];

    return (
        <AppLayout breadcrumbs={breadcrumbs}>
            <Head title="Edit Store Category" />
            <div className="flex h-full flex-1 flex-col gap-4 overflow-x-auto rounded-xl p-4">
                <StoreCategoryForm category={category} type="edit" />
            </div>
        </AppLayout>
    )
}

export default StoreCategoriesEdit

