import { Form, router } from '@inertiajs/react'
import {
    Card,
    CardContent,
    CardDescription,
    CardFooter,
    CardHeader,
    CardTitle,
} from '@/components/ui/card'
import { Field, StoreCategory } from '@/types/dashboard'
import FormButtons from '@/components/form/form-buttons'
import TranslatableTabs from '@/components/form/translatable-tabs'
import { normalizeFieldValue } from '@/lib/utils'
import AlertError from '@/components/alert-error'

// Routes will be auto-generated by wayfinder
const storeCategoryRoutes = {
    index: { url: () => '/admin/store-categories' },
    store: { url: () => '/admin/store-categories' },
    update: { url: (args: { 'store-category': string | number }) => `/admin/store-categories/${args['store-category']}` },
}

interface StoreCategoryFormProps {
    category: StoreCategory;
    type: 'create' | 'edit';
}

export default function StoreCategoryForm({ category, type }: StoreCategoryFormProps) {
    const fields: Field[] = [
        {
            name: 'name',
            label: 'Name',
            type: 'text',
            value: normalizeFieldValue(category.name),
            required: true,
        },
        {
            name: 'description',
            label: 'Description',
            type: 'textarea',
            value: normalizeFieldValue(category.description),
            required: false,
        },
    ];

    return (
        <Form
            method={type === 'edit' ? 'put' : 'post'}
            action={
                (type === 'edit' && category.id)
                    ? storeCategoryRoutes.update.url({ 'store-category': category.id })
                    : storeCategoryRoutes.store.url()
            }
        >
            {({ processing, errors }) => (
                <Card>
                    <CardHeader>
                        <CardTitle>
                            {type === 'create' ? 'Create Store Category' : 'Edit Store Category'}
                        </CardTitle>
                        <CardDescription>
                            {type === 'create' ? 'Add a new store category' : 'Update store category information'}
                        </CardDescription>
                    </CardHeader>
                    <CardContent className="space-y-4">
                        <TranslatableTabs fields={fields} errors={errors} />
                    </CardContent>
                    <CardFooter>
                        <FormButtons
                            handleCancel={() => router.visit(storeCategoryRoutes.index.url())}
                            processing={processing}
                            isEditMode={type === 'edit'}
                        />
                    </CardFooter>
                </Card>
            )}
        </Form>
    );
}

